### ISSUE TITLE
Improve registration

### ISSUE THREAD

**Issue by VojtechVidra** [RBND-studio/flows-cloud#165]
- [ ] Find out if we can help user with registration when the account exists but is not verified yet
- [ ] Screen with resend registration verification. Discuss do we want to put it?
- [ ] When SSO user tries to register with email no verification email is actually sent

**Comment by OPesicka** [comment]
@VojtechVidra pls figure out what to do we want to do here

**Comment by VojtechVidra** [comment]
First two points are the same thing. When user is not verified and tries to login, error shows up with message that they are not verified. User can then go to registration and fill the registration again, which will resend the verification email.
Question is if we want to help the user so they are able to verify their account or we keep it as it is?

The last point is edgecase which imo doesn't have to be solved.

**Comment by VojtechVidra** [comment]
@OPesicka what do you think, should we close this for now?
