### ISSUE TITLE
Fix me endpoint

### ISSUE THREAD

**Issue by VojtechVidra** [RBND-studio/flows-cloud#487]
`apps/backend/src/members/members.service.ts:52` can throw error thanks to duplicate primary key. What I suspect is actually happening is that in the background the `user_metadata` object gets created in the DB as a part of another API request. This could be fixed by upserting the `user_metadata` instead of checking if it exists in the code.

**Comment by pesickadavid** [comment]
This is probably a concurency issue, we're fetching the `/me` endpoint on multiple places and if somebody speedruns the signup process there is a possibility to hit the endpoint twice in a matter of miliseconds.
