### ISSUE TITLE
Setup github environment

### ISSUE THREAD

**Issue by OPesicka** [RBND-studio/flows-cloud#6]
- [x]  Split secrets into individual entries - https://cli.github.com/manual/gh_secret_set
- [x]  Env setup
- [x] Document the setup

**Comment by pesickadavid** [comment]
Secrets nastavený, jen k tomu dodělám dokumentaci ať víme jak to upravit do budoucna

**Comment by OPesicka** [comment]
Ping @pesickadavid

**Comment by VojtechVidra** [comment]
Ještě prosím použít ty secrets ve workflows 😄

**Comment by OPesicka** [comment]
And setup [gitleaks](https://github.com/marketplace/actions/gitleaks)? @VojtechVidra @pesickadavid

**Comment by VojtechVidra** [comment]
Don't forget to apply the environment to the workflow. I just spent past 30 minutes debugging this 😄 
https://stackoverflow.com/questions/66521958/how-to-access-environment-secrets-from-a-github-workflow

**Comment by VojtechVidra** [comment]
- [ ] Replace existing stage secrets with new ones to make sure we're not leaving something open thanks to past github commits
- [ ] Fix supabase studio basic auth secrets, I would prefer to find a better solution for supabase studio auth. Maybe Authelia? https://youtu.be/wyUr_U6Cma4?t=1551
