### ISSUE TITLE
Spell checker

### ISSUE THREAD

**Issue by VojtechVidra** [RBND-studio/flows-cloud#60]
Maybe we can use this: https://www.npmjs.com/package/cspell
Or maybe there is something else, I haven't looked.
Hopefully there will be enough configuration for us to define custom words, like `Flows` and others. During the implementation the task will crystalize.. 😄

**Comment by pesickadavid** [comment]
Install this [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) VS Code extension to catch typos on the fly. The rest will be handled by `cspell` in pre-commit hook
